services:
    apache:
        build: etc/apache
        restart: unless-stopped
        depends_on:
            - php
        ports:
            - 8000:80
        volumes:
            - ./:/srv

    php:
        build: etc/php
        restart: unless-stopped
        depends_on:
            - mysql
        environment:
            MYSQL_HOST: mysql
            MYSQL_PORT: 3306
            MYSQL_DATABASE: app
            MYSQL_USER: app
            MYSQL_PASSWORD: app
        volumes:
            - ./:/srv

    mysql:
        image: mysql:8.3
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: app
            MYSQL_USER: app
            MYSQL_PASSWORD: app
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - mysql:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.2
        restart: unless-stopped
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        ports:
            - 8001:80

volumes:
    mysql: ~
